const objectNames = {
    korean: {
        badminton: "배드민턴 라켓",
        ball: "피구공",
        books: "책더미",
        bookshelf: "교실 앞 책장",
        bulletin1: "게시판",
        bulletin2: "게시판",
        cam: "캠코더", // 수정된 부분
        car1: "자동차1",
        car2: "자동차2",
        car3: "자동차3",
        car4: "자동차4",
        cat: "고양이",
        door_classroom: "교실 문",
        door_gyo: "교무실 문",
        door_mae: "매점 문",
        door_store: "매점문",
        door_wc1: "1층 화장실 문",
        door_wc2: "2층 화장실 문",
        elevator1: "1층 엘리베이터",
        exit_to_front: "정문 출구",
        elevator2: "2층 엘리베이터",
        front_gate: "정문",
        guryeong: "구령대",
        letter1: "편지",
        letter2: "편지",
        letter3: "편지",
        locker: "우편함",
        nca: "NCA 전단지",
        line_machine: "라인 페인터",
        plant1: "화분1",
        plant2: "화분2",
        plant3: "화분3",
        pot1: "큰 화분",
        pot2: "작은 화분",
        shelf1: "책장1",
        shelf2: "1층 로비 선반",
        shelf3: "책장3",
        shelf4: "책장4",
        sink: "식수대",
        stair_to_third: "3층 계단",
        window: "창문",
    },
    english: {
        badminton: "Badminton Racket",
        ball: "Dodgeball",
        books: "Books",
        bookshelf: "Bookshelf in Front of Classroom",
        bulletin1: "Bulletin Board",
        bulletin2: "Bulletin Board",
        cam: "Camcorder", // 수정된 부분
        car1: "Car 1",
        car2: "Car 2",
        car3: "Car 3",
        car4: "Car 4",
        cat: "Cat",
        door_classroom: "Classroom Door",
        door_gyo: "Teachers' Office Door",
        door_mae: "School Store Door",
        door_store: "Store Door",
        door_wc1: "1F Restroom Door",
        door_wc2: "2F Restroom Door",
        elevator1: "1F Elevator",
        exit_to_front: "Exit to Front",
        elevator2: "2F Elevator",
        front_gate: "Front Gate",
        guryeong: "Platform",
        letter1: "Saerom's Letter",
        letter2: "Warning Letter",
        letter3: "Philosophical Letter",
        locker: "Mailbox",
        nca: "NCA", // 추가된 부분
        line_machine: "Line Painter",
        plant1: "Plant 1",
        plant2: "Plant 2",
        plant3: "Plant 3",
        pot1: "Large Pot",
        pot2: "Small Pot",
        shelf1: "Bookshelf 1",
        shelf2: "1F Lobby Shelf",
        shelf3: "Bookshelf 3",
        shelf4: "Bookshelf 4",
        sink: "Water Fountain",
        stair_to_third: "Stairs to 3F",
        window: "Window",
    },
};

const objectDialogues = {
    korean: {
        badminton: [
            "(배드민턴 라켓이다.)",
            "(체육 시간에 사용하는 것 같다.)",
            "(네트 너머로 셔틀콕을 쳐서 보내는 스포츠지.)",
            "(라켓이 가벼워 보인다.)",
            "(배드민턴은 의외로 격렬한 운동이야.)",
        ],
        ball: [
            "(피구공이다.)",
            "(운동장에서 주로 사용하는 공이다.)",
            "(지금은 굴러다니고 있지 않다.)",
        ],
        books: ["(여기저기 책이 쏟아져 있다. 누가 떨어뜨린 걸까?)"],
        bookshelf: ["(교실 앞에 놓인 책장이다. 참고서와 문제집이 꽂혀 있다.)"],
        bulletin1: [
            "(학교 게시판이다.)",
            "(각종 공지사항과 학교 행사 안내가 붙어있다.)",
            "(「다음주 토요일 체육대회 개최」)",
            "(「도서관 신간도서 입고 안내」)",
            "(「학생회장 선거 공고」)",
            "(여러 중요한 정보들이 있다.)",
        ],
        bulletin2: [
            "(교무실 앞 게시판이다.)",
            "(선생님들 관련 안내와 교직원 공지가 붙어있다.)",
            "(「교사 회의 일정: 매주 수요일 16:00」)",
            "(「교직원 건강검진 안내」)",
            "(「학생 상담 일정표」)",
            "(학생들은 참고만 하라는 안내문도 있다.)",
        ],
        cam: [
    
            "(오래된 캠코더다.)",
            "(누군지 모를 선배들의 사진이 보인다.)",
            "(같은 교복을 입고 환하게 웃고 있다.)",
            "(...이게 왜 바닥에 떨어져있지?)",
            "(언제부터 있었던걸까?)",
        ], 
        car1: [
            "(학교 앞에 주차된 자동차다.)",
            "(선생님들이 타고 오시는 차인 것 같다.)",
            "(번호판을 보니 서울 차량이네.)",
            "(깔끔하게 관리되고 있는 것 같다.)",
            "(아마 교무실 선생님 차일 거야.)",
        ],
        car2: [
            "(또 다른 자동차가 주차되어 있다.)",
            "(이 차는 조금 오래된 것 같다.)",
            "(하지만 여전히 잘 관리되고 있어 보인다.)",
            "(아마 체육 선생님 차가 아닐까?)",
            "(트렁크에 운동용품이 들어있을 것 같다.)",
        ],
        car3: [
            "(세 번째 자동차다.)",
            "(차량 내부가 깔끔하게 정리되어 있다.)",
            "(조수석에 서류가 정리되어 있는 게 보인다.)",
            "(아마 교장선생님이나 교감선생님 차인 것 같다.)",
            "(학교 관련 업무용 차량 같아 보인다.)",
        ],
        car4: [
            "(네 번째 자동차가 주차되어 있다.)",
            "(이 차는 좀 더 작고 실용적이어 보인다.)",
            "(뒷좌석에 가방이 놓여있는 게 보인다.)",
            "(젊은 선생님이 타고 다니는 차 같다.)",
            "(연료비 절약을 위해 소형차를 선택한 것 같다.)",
        ],
        cat: [
            "야옹~ 야옹~",
            "(학교 고양이인 것 같다.)",
            "(이름표를 보니 '나비'라고 적혀있다.)",
            "(털이 부드러워 보인다.)",
            "야옹~",
        ],
        door_classroom: [
            "(교실로 들어가는 문이다. 안에서 선생님이 수업하는 소리가 들린다.)",
            "숙제 안해온 사람 당장 나와!",
            "(누가 혼나는 것 같은데...?)",
            "(지금은 들어가면 안 될 것 같다...)",
        ],
        door_gyo: [
            "(교무실로 들어가는 문이다.)",
            "너 복장이 그게 뭐야!!!",
            "(안에서 학생들이 복장 불량으로 혼나는 소리가 들린다.)",
            "(지금은 들어가면 안 될 것 같다...)",
        ],
        door_store: [
            "(학교 매점 문이다.)",
            "(문이 잠겨있어서 들어갈 수 없다.)",
            "(매점 운영시간이 아닌 것 같다.)",
            "(점심시간이 되면 문을 열까?)",
        ],
        door_wc1: [
            "(1층 화장실 문이다.)",
            "(콸콸... 물소리가 계속 들려온다.)",
            "(누군가 수도꼭지를 틀어놓고 간 것 같다.)",
            "(아니면... 혹시 귀신이라도 있는 건 아니겠지?)",
            "(문을 두드려볼까...? 아니야, 그냥 지나가자.)",
        ],
        door_wc2: [
            "(2층 화장실 문이다.)",
            "(왠지 괜히 음산한 기분이 드는데...)",
            "(...내가 아까 잘못본거겠지...?)",
        ],
        elevator1: [
            "(1층에 있는 학교 엘리베이터다.)",
            "(2층과 3층으로 이동할 수 있는 것 같다.)",
            "(학생은 사용할 수 없는 것 같다.)",
            "(계단을 이용하자.)",
        ],
        elevator2: [
            "(학교 엘리베이터다.)",
            "(1층과 3층으로 이동할 수 있는 것 같다.)",
            "(학생은 사용할 수 없는 것 같다.)",
            "(계단을 이용하자.)",
        ],
        exit_to_front: [
            "(1층에서 정문으로 나가는 출구다.)",
            "(학교 밖으로 나갈 수 있을 것 같다.)",
            "(수업시간이라 나가도 될까?)",
            "(정문 쪽으로 이어진다.)",
        ],
        front_gate: [
            "(은하여자고등학교 정문이다.)",
            "(수업시간에는 문이 잠겨있어서 나갈 수 없다.)",
            "(간혹 담을 넘는 학생들이 있기도 하다.)",
            "(지금은 꽉 잠겨있는 듯 하다.)",
        ],
        guryeong: [
            "(학교 구령대인 것 같다.)",
            "(입학실 내용을 떠올려보자면...)",
            "(매주 월요일 조회시간에 이곳에서 교장선생님의 훈화가 있다고 했다.)",
            "(구령대 아래 철문을 열면 피구공과 같은 운동용품들이 들어있다.)",
            "(...소문에 따르면 저녁에 구령대 쪽에서 이상한 소리가 난다고 했다.)",
            "(흔한 학교 괴담일까?)",
        ],
        letter1: [
            "(사라얌!! 나 새롬쓰 ><)",
            "(지금 5교신데 수업 개길음 -ㅅ-)",
            "(배고파 죽겠는데 왜케 안끝나냐고!!! 오나전 짜증...)",
            "(요새도 다이어트함? 끝나고 나나분식 ㄱ?)",
            "(방금 이거 쓰면서 침고임...)",
            "(그럼 이따 가는거다?! 약속!!!!!)",
            "(-새롬쓰-)",
        ],
        letter2: [
            "(혼자 읽으시오)",
            "(이 편지를 발견한 너에게 나만 아는 사실을 알려줄게...)",
            "(12시 이후에 미술실에 들어가지마.)",
            "(이유는 묻지말고...)",
            "(난 분명히 말했어. 들어가지마...!)",
        ],
        letter3: [
            "(심연을 오랫동안 들여다보면, 그 심연 또한 나를 들여다본다. - 니체)",
            "(책 읽는거 좋아해? 내가 제일 좋아하는 문구야!)",
            "(근데 우리 학교에서도 심연이 존재하는 거 알고 있어...?)",
            "(거길 가면 자기 자신의 심연을 들여다볼 수 있지.)",
            "(어디냐면...바로...)",
            "(...)",
            "(이후 내용은 지워져 있다.)",
        ],
        locker: [
            "(종종 학교에 우편이 오는 모양이다.)",
            "(선생님들과 행정실 직원분들이 주로 쓰는 것 같다.)",
            "(잠금장치가 있어서 열 수 없다.)",
        ],
        nca: [
            "(...NCA? 뉴콘텐츠아카데미?)",
            "(그거 설마 신기술 콘텐츠 분야를 선도하는 융합인재를 양성하는 곳이야?)",
            "(...)",
            "(...멋진데...?!?)",
        ],
        line_machine: [
            "(운동장 라인을 그리는 페인터 기계다.)",
            "(운동장의 흰 라인들이 이 기계로 그어진 것 같다.)",
            "(체육대회나 운동회 준비 때 사용하는 것 같다.)",
            "(지금은 사용하지 않는 것 같다.)",
        ],
        plant1: [
            "(학교 복도에 놓인 화분이다.)",
            "(초록색 잎이 싱싱해 보인다.)",
            "(누군가 정성스럽게 관리하고 있는 것 같다.)",
        ],
        plant2: [
            "(또 다른 화분이다.)",
            "(열대 식물처럼 잎이 크고 넓어보인다.)",
            "(싱그러운 향기가 난다.)",
        ],
        plant3: ["(작은 화분이다.)", "(물을 잘 주고 있는 모양이다.)"],
        pot1: [
            "(학교 복도에 놓인 큰 화분이다.)",
            "(키가 큰 관엽식물이 자라고 있다.)",
            "(잎이 무성하고 건강해 보인다.)",
            "(이런 큰 화분은 공기 정화에 도움이 될 것 같다.)",
            "(누군가 정성스럽게 키우고 있는 게 느껴진다.)",
            "(화분 받침대도 깔끔하게 정리되어 있다.)",
        ],
        pot2: [
            "(작은 화분이 놓여있다.)",
            "(앙증맞은 크기의 다육식물이 심어져 있다.)",
            "(통통한 잎이 귀여워 보인다.)",
            "(물을 많이 주지 않아도 잘 자라는 식물 같다.)",
            "(작지만 생명력이 강해 보인다.)",
            "(교실 창가에 두면 딱 좋을 크기다.)",
        ],
        shelf1: [
            "(1층 로비에 놓인 안내 선반이다.)",
            "(학교 소개 팜플렛과 각종 안내 자료가 가득하다.)",
            "(「은하여고 입학 안내서」)",
            "(「동아리 활동 소개」)",
            "(「진학 상담 신청서」)",
            "(방문객들이 학교 정보를 얻어갈 수 있도록 마련된 것 같다.)",
            "(신입생 부모님들이 자주 가져가는 모양이다.)",
            "(학교 홍보용 달력과 기념품도 몇 개 보인다.)",
        ],
        shelf2: [
            "(1층 로비에 놓인 또 다른 선반이다.)",
            "(학교 행사 포스터와 공지사항이 가득 붙어 있다.)",
            "(「체육대회 안내 - 10월 15일 개최」)",
            "(「동아리 박람회 - 신입 부원 모집 중!」)",
            "(「진로 상담 신청 - 진로진학상담부」)",
            "(「학교 축제 준비위원회 모집」)",
            "(「장학금 신청 안내」)",
            "(포스터들이 층층이 붙어있어 거의 전쟁터 같다.)",
            "(몇몇 포스터는 이미 마감된 것 같은데도 아직 붙어있다.)",
            "(선반 위에는 동아리 홍보 전단지와 각종 신청서가 놓여있다.)",
            "(...새 학기가 되면 더 복잡해질 것 같다.)",
        ],
        shelf3: [
            "(교무실 근처에 놓인 높은 책장이다.)",
            "(각종 교육 서류와 참고서가 빼곡히 꽂혀있다.)",
            "(「학생 생활 지도서」「교육과정 안내」등의 책들이 보인다.)",
        ],
        shelf4: [
            "(교무실 근처에 놓인 또 다른 책장이다.)",
            "(오래된 자료와 공문들이 년도별로 정리되어 쌓여 있다.)",
            "(먼지가 쌓인 것을 보니 자주 사용하지 않는 것 같다.)",
        ],
        sink: [
            "(학교 식수대다.)",
            "(차가운 물이 나올 것 같다.)",
            "(운동 후에 목이 마를 때 유용하겠네.)",
            "(지금은 물을 마실 필요가 없을 것 같다.)",
        ],
        stair_to_third: [
            "(3층으로 올라가는 계단이다.)",
            "(발걸음 소리가 희미하게 들려온다.)",

            "(계단 입구에 '학생 출입 제한' 표시가 붙어있다.)",

            "(...위에서 무슨 일이 일어나고 있는 걸까?)",

            "(나중에 다시 와봐야겠다.)",
        ],

        window: [
            "(창문 너머로 학교 뒤편 풍경이 보인다.)",
            "(운동장과 산이 조용하다.)",
        ],
    },
    english: {
        badminton: [
            "(This is a badminton racket.)",
            "(It seems to be used during PE class.)",
            "(It's a sport where you hit the shuttlecock over the net.)",
            "(The racket looks lightweight.)",
            "(Badminton is surprisingly intense exercise.)",
        ],
        ball: [
            "(This is a dodgeball.)",
            "(It's a ball mainly used in the playground.)",
            "(It's not rolling around right now.)",
        ],
        books: ["(Books are scattered everywhere. Who dropped them?)"],
        bookshelf: [
            "(A bookshelf in front of the classroom. It's filled with reference books and workbooks.)",
        ],
        bulletin1: [
            "(This is the school bulletin board.)",
            "(Various announcements and school event notices are posted.)",
            "「Sports Day next Saturday」",
            "「New books available at the library」",
            "「Student council election notice」",
            "(There's lots of important information here.)",
        ],
        bulletin2: [
            "(This is the bulletin board in front of the teachers' office.)",
            "(Notices for teachers and staff are posted here.)",
            "「Teachers' meeting: Every Wednesday 4pm」",
            "「Staff health checkup notice」",
            "「Student counseling schedule」",
            "(There's a note saying students should only refer to this board.)",
        ],
        cam: [
            // 수정된 부분
            "(An old camcorder.)",
            "(I can see photos of some unknown seniors.)",
            "(They're wearing the same school uniform and smiling brightly.)",
            "(...Why is this lying on the floor?)",
            "(How long has it been here?)",
        ], // 수정된 부분
        car1: [
            "(A car parked in front of the school.)",
            "(It seems to be a teacher's car.)",
            "(Looking at the license plate, it's a Seoul vehicle.)",
            "(It looks well-maintained and clean.)",
            "(Probably belongs to a teacher from the faculty office.)",
        ],
        car2: [
            "(Another car is parked here.)",
            "(This car looks a bit older.)",
            "(But it still seems well-maintained.)",
            "(Maybe it's the PE teacher's car?)",
            "(There might be sports equipment in the trunk.)",
        ],
        car3: [
            "(The third car.)",
            "(The interior is neatly organized.)",
            "(I can see documents organized in the passenger seat.)",
            "(Probably belongs to the principal or vice principal.)",
            "(Looks like a vehicle for school-related business.)",
        ],
        car4: [
            "(The fourth car is parked here.)",
            "(This car looks smaller and more practical.)",
            "(I can see a bag placed in the back seat.)",
            "(Looks like a young teacher's car.)",
            "(Probably chose a compact car to save on fuel costs.)",
        ],
        cat: [
            "Meow~ Meow~",
            "(It seems to be the school cat.)",
            "(Looking at the name tag, it says 'Butterfly'.)",
            "(Its fur looks soft.)",
            "Meow~",
        ],
        door_classroom: [
            "(This is the door to a classroom. You can hear the teacher's voice from inside.)",
            "Those who didn't do homework, come out right now!",
            "(Someone seems to be getting scolded...?)",
            "(I probably shouldn't go in right now...)",
        ],
        door_gyo: [
            "(This is the door to the teachers' office.)",
            "What's with that outfit!!!",
            "(You can hear students being scolded for dress code violations inside.)",
            "(I probably shouldn't go in right now...)",
        ],
        door_store: [
            "(This is the school store door.)",
            "(The door is locked and I can't enter.)",
            "(It's not store operating hours.)",
            "(Maybe it opens during lunch time?)",
        ],
        door_wc1: [
            "(This is the 1st floor restroom door.)",
            "(Splash splash... water sounds keep coming from inside.)",
            "(Someone seems to have left the faucet running.)",
            "(Or... could there be a ghost?)",
            "(Should I knock on the door...? No, let's just pass by.)",
        ],
        door_wc2: [
            "(This is the 2nd floor restroom door.)",
            "(Somehow I get an eerie feeling...)",
            "(...I must have seen it wrong earlier...?)",
        ],
        elevator1: [
            "(This is the school elevator on the 1st floor.)",
            "(It seems to go to the 2nd and 3rd floors.)",
            "(Students can't use it.)",
            "(Let's use the stairs.)",
        ],
        elevator2: [
            "(This is the school elevator.)",
            "(It seems to go to the 1st and 3rd floors.)",
            "(Students can't use it.)",
            "(Let's use the stairs.)",
        ],
        exit_to_front: [
            "(This is the exit from the 1st floor to the front gate.)",
            "(It seems like you can go outside the school.)",
            "(Is it okay to leave during class time?)",
            "(It leads towards the front gate.)",
        ],
        front_gate: [
            "(This is Eunha Girls' High School's main gate.)",
            "(The gate is locked during class hours, so you can't leave.)",
            "(Sometimes there are students who climb over the fence.)",
            "(It seems tightly locked right now.)",
        ],
        guryeong: [
            "(This seems to be the school podium.)",
            "(Let me recall the entrance ceremony...)",
            "(Every Monday morning during assembly, the principal gives a speech here.)",
            "(If you open the iron door under the podium, there are sports equipment like dodgeballs.)",
            "(...According to rumors, strange sounds come from the podium area in the evening.)",
            "(Is it just a common school ghost story?)",
        ],
        letter1: [
            "(Sara!! It's me, Saerom ><)",
            "(I'm in 5th period right now and class is so boring -ㅅ-)",
            "(I'm starving but why won't it end!!! So annoying...)",
            "(Are you still dieting? Want to go to Nana's snack bar after this?)",
            "(I'm drooling just writing this...)",
            "(So we're going later, right?! Promise!!!!!)",
            "(-Saerom-)",
        ],
        letter2: [
            "(Read this alone)",
            "To you who found this letter, I'll tell you something only I know...",
            "Don't go into the art room after midnight.",
            "Don't ask why...",
            "I told you clearly. Don't go in...!",
        ],
        letter3: [
            "If you gaze long enough into an abyss, the abyss will gaze back into you. - Nietzsche",
            "Do you like reading books? This is my favorite quote!",
            "But did you know that an abyss exists in our school too...?",
            "If you go there, you can look into the abyss of yourself.",
            "Where is it... right...",
            "(The rest of the content has been erased.)",
        ],
        locker: [
            "(It seems mail often comes to the school.)",
            "(Teachers and administrative staff seem to use this mainly.)",
            "(There's a locking mechanism so I can't open it.)",
        ],
        nca: [
            // 추가된 부분
            "(...NCA? New Contents Academy?)",
            "(Isn't that the place that leads the new technology content field and nurtures convergent talents?)",
            "(...)",
            "(...That's amazing...?!?)",
        ], // 추가된 부분
        line_machine: [
            "(This is a line painter machine for the playground.)",
            "(The white lines on the playground seem to be drawn with this machine.)",
            "(It's probably used for preparing sports days or athletic meets.)",
            "(It doesn't seem to be in use right now.)",
        ],
        plant1: [
            "(This is a potted plant in the school hallway.)",
            "(The green leaves look fresh.)",
            "(Someone seems to be taking good care of it.)",
        ],
        plant2: [
            "(This is another potted plant.)",
            "(It has large, broad leaves like a tropical plant.)",
            "(It has a fresh fragrance.)",
        ],
        plant3: [
            "(This is a small potted plant.)",
            "(It seems to be well watered.)",
        ],
        pot1: [
            "(This is a large pot placed in the school hallway.)",
            "(A tall foliage plant is growing in it.)",
            "(The leaves look lush and healthy.)",
            "(Such a large pot would help purify the air.)",
            "(I can feel that someone is taking good care of it.)",
            "(The pot saucer is also neatly arranged.)",
        ],
        pot2: [
            "(A small pot is placed here.)",
            "(Cute-sized succulents are planted in it.)",
            "(The plump leaves look adorable.)",
            "(It seems like a plant that grows well without much watering.)",
            "(Small but looks very vital.)",
            "(It would be perfect size to place by a classroom window.)",
        ],
        shelf1: [
            "(This is an information shelf in the 1st floor lobby.)",
            "(It's full of school introduction pamphlets and various information materials.)",
            "「Eunha Girls' High School Admission Guide」「Club Activity Introduction」「Career Counseling Application」",
            "(It seems to be prepared for visitors to get school information.)",
            "(Parents of new students seem to take them frequently.)",
            "(I can also see some promotional calendars and souvenirs.)",
        ],
        shelf2: [
            "(This is another shelf in the 1st floor lobby.)",
            "(School event posters and announcements are fully attached.)",
            "(「Sports Day Information - October 15th」)",
            "(「Club Fair - New Members Wanted!」)",
            "(「Career Counseling Application - Career Guidance Office」)",
            "(「School Festival Planning Committee Recruitment」)",
            "(「Scholarship Application Guide」)",
            "(The posters are layered on top of each other like a battlefield.)",
            "(Some posters seem to be past their deadline but still hanging.)",
            "(On top of the shelf are club promotional flyers and various application forms.)",
            "(...It'll probably get even more complicated when the new semester starts.)",
        ],
        shelf3: [
            "(A tall bookshelf near the teachers' office.)",
            "(Educational documents and reference books are packed tightly.)",
            "(I can see books like 'Student Life Guide' and 'Curriculum Information'.)",
        ],
        shelf4: [
            "(Another bookshelf near the teachers' office.)",
            "(Old files and official documents are organized by year.)",
            "(It looks dusty, so it's probably not used very often.)",
        ],
        sink: [
            "(This is the school water fountain.)",
            "(Cold water should come out from here.)",
            "(It would be useful when I'm thirsty after exercising.)",
            "(I don't need to drink water right now.)",
        ],
        stair_to_third: [
            "(These are stairs going up to the 3rd floor.)",
            "(Faint footsteps can be heard.)",
            "(There's a 'Student Access Restricted' sign at the entrance.)",
            "(...What's happening up there?)",
            "(I should come back later.)",
        ],

        student40: [
            "Ugh, my bangs look a bit greasy today...",
            "Do you have a comb?",
        ],
        student41: [
            "Damn... the vending machine ate my coins again...",
        ],
        student42: [
            "Science is really fascinating...",
            "I'm going to study chemistry and become a researcher.",
        ],
        student43: [
            "(She's organizing her locker.)",
        ],
        student44: [
            "I'm useless...",
            "I failed the quiz... I'm trash...",
        ],
        student45: [
            "Harry Potter is so interesting that I kept reading, taking a break now...",
            "I wonder who took the next volume...",
            "I wish they'd return it soon.",
        ],
        student46: [
            "I don't want to go into the classroom......",
        ],

        window: [
            "(Through the window, you can see the scenery behind the school.)",
            "(The playground and mountains are quiet.)",
        ],
    },
    names: objectNames, // 이름 정보 추가
};

export default objectDialogues;
