const creditText = {
    korean: [
        "After School RPG",
        "",
        "Gong Dong Chae Presents",
        "",
        "Planning",
        "All Team Members: ",
        "Yoonmyung Kim",
        "Eunseo Park",
        "Nayoung Lee",
        "Boyoung Kim",
        "",
        "Project Lead",
        "Eunseo Park",
        "",

        "Tech Lead & Game Level Design",
        "Yoonmyung Kim",
        "",
        "Art Lead",
        "Nayoung Lee",
        "",
        "Special Thanks To...",
        "Seongmin Lee",
        "Taewon Kim",
        "Boram Lee",
        "New Contents Academy",
        "To those who gave feedback",
        "To the open source community",
        "",
        "",
        "Tools Used",
        "JavaScript & Kaboom.js",
        "Tiled Map Editor",
        "VS Code",
        "Git & GitHub",
        "",
        "",
        "Libraries & Assets",
        "Kaboom.js - Game Engine",
        "Web Audio API - Sound",
        "Canvas API - Graphics",
        "Font Assets - Typography",
        "",
        "",
        "Thank you for playing!",
        "",
        "© 2025 After School!!! RPG WEB",
        "All rights reserved.",
        "",
        "Made with ❤️ in JavaScript",
    ],
    english: [
        "After School RPG",
        "",
        "Gong Dong Chae Presents",
        "",
        "Planning",
        "All Team Members: ",
        "Yoonmyung Kim",
        "Eunseo Park",
        "Nayoung Lee",
        "Boyoung Kim",
        "",
        "Project Lead",
        "Eunseo Park",
        "",

        "Tech Lead & Game Level Design",
        "Yoonmyung Kim",
        "",
        "Art Lead",
        "Nayoung Lee",
        "",
        "Special Thanks",
        "Seongmin Lee",
        "Taewon Kim",        
        "Boram Lee",
        "New Contents Academy",
        "To those who gave feedback",
        "To the open source community",
        "",
        "",
        "Tools Used",
        "JavaScript & Kaboom.js",
        "Tiled Map Editor",
        "VS Code",
        "Git & GitHub",
        "",
        "",
        "Libraries & Assets",
        "Kaboom.js - Game Engine",
        "Web Audio API - Sound",
        "Canvas API - Graphics",
        "Font Assets - Typography",
        "",
        "",
        "Thank you for playing!",
        "",
        "© 2025 After School!!! RPG WEB",
        "All rights reserved.",
        "",
        "Made with ❤️ in JavaScript",
    ],
};

export default creditText;
